### PR TITLE
Changing the size of the info icon and edit introduction text

### PR DESCRIPTION
**Pull request by jinalfoflia**
The information icon (i) is subtle, to make it more visible, I have changed the size of the icon.

_Before_ 👇 
screen shot 2017-08-02 at 5 30 36 pm

--- 

_After_ 👇 
screen shot 2017-08-02 at 5 29 49 pm

### Next action[s]

- [ ] Re-look into the introduction text

### CODE REVIEW

**Comment by jinalfoflia** [comment]
@katydecorah the text in the information container is overflowing, is there a way we could increase the size of this container? I'd love to also know if increasing the `information` icon's size is getting well with the styling of the page.

screen shot 2017-08-02 at 8 45 00 pm


@mikelmaron I have made some tweaks to the introduction text, it'll be great to have your 👀  before we merge it.

**Comment by katydecorah** [comment]
@jinalfoflia To fix the height on the information box try changing this line https://github.com/mapbox/mapping/blob/b6fd3c3b757f7e477a3fbae1e55fc79660f48478/site.css#L232 to `height: 380px;`

**Comment by jinalfoflia** [comment]
> @jinalfoflia To fix the height on the information box try changing this line https://github.com/mapbox/mapping/blob/b6fd3c3b757f7e477a3fbae1e55fc79660f48478/site.css#L232 to height: 380px;

@katydecorah it works, thank you so much! 🎉

**Comment by jinalfoflia** [comment]
Thank you @mikelmaron and @katydecorah for the review 🙇‍♀️

**Comment by oini** [comment]
Looks so much better now! ❤️

**Pull request merged**
