### PR TITLE
fix translation.yml to fit Japanese translation

### PR DESCRIPTION
**Pull request by nyampire**

### CODE REVIEW

**Comment by jinalfoflia** [comment]
Hey @nyampire, I'm finding the following error while running this file locally:

image

Can you please look into it?

**Comment by nyampire** [comment]
I added 2 files to display JP pages.

But couldn't succeed enact switch button at home. (only espaniol)
I guess it might depends on pager.html or around there. 
Perhaps it would be a depends with design matter.

Any suggestions?

**Comment by nyampire** [comment]
additionally, it is trivial and another issue. I found it is counted double for page count on top page.

**Comment by jinalfoflia** [comment]
@katydecorah can you please help with this issue - https://github.com/mapbox/mapping/pull/301#issuecomment-307561805 and also I'm unable to understand why are the number of guides shown double in number (https://github.com/mapbox/mapping/pull/301#issuecomment-307562661)

cc: @maning @nyampire

**Comment by katydecorah** [comment]
@nyampire hello there! In #302, I've fixed some of the issues you're seeing! Please try updating your branch with the latest from mb-pages and uncommenting this line: https://github.com/mapbox/mapping/blob/2a0a47f87751fb234a882574a8e56cdfd7b65115/_config.yml#L17

Everything should be working correctly now. Please let us know if you find more bugs. Thanks for contributing!

**Comment by nyampire** [comment]
Thank you so much.
It works!!

**Comment by katydecorah** [comment]
@nyampire Looks great! Do you have any more edits? If not, I'll merge!

**Comment by nyampire** [comment]
Please merge them if they are able to merge 👍 

I have other files to almost ready.
But I would like to review them, will take some days.

**Comment by katydecorah** [comment]
sounds good, @nyampire. Thank you!

@jinalfoflia we should tweet this :)

**Comment by jinalfoflia** [comment]
Thank you for all the help @katydecorah!

> @jinalfoflia we should tweet this :)

Yes, will schedule some tweets on this! :)

**Pull request merged**
