### PR TITLE
Navigation guide

### PR DESCRIPTION
**Pull request by abhisheksaikia**
navigation_guide

@maning @planemad Can you review the contents once more and merge the PR if it is 🆗  to go?

### CODE REVIEW

**Comment by planemad** [comment]
👍

**Comment by planemad** [comment]
Can we have a better SEO relevant url than `/mapping/mapping-to-improve-navigation/` ? @abhisheksaikia @jothirnadh @maning

**Comment by abhisheksaikia** [comment]
The navigation guide is has been 👀  at and is ready to be merged. @tatsvc I am having a problem with the header imagery not aligning properly for the guide when I changed the title. Can you please have a look at it and fix the issue?

**Comment by planemad** [comment]
screenshot 2016-10-24 17 44 44

Even changing a single letter in the title is causing this. No idea what magic is going on @tatsvc

**Comment by tatsvc** [comment]
oh wow! that's odd! let me take a look!

**Comment by tatsvc** [comment]
oh so yes, some of these images have some custom css, to make sure the image doesn't overlap with the text, but by changing the title of the guide, you also changed the id `#mapping-for-navigation svg ` that I was using to target this image!

Should be all fixed now!

**Comment by abhisheksaikia** [comment]
Great @tatsvc. Thanks for fixing this 🙏 . Merging it.

**Pull request merged**
