### PR TITLE
mb-pages Japanese translation

### PR DESCRIPTION
**Pull request by nyampire**
Thank you for great mapping documents.
I made some translation files of Japanese version.

Please check if those files could be merged.

### CODE REVIEW

**Comment by nyampire** [comment]
I've posted a piece of docs at [here](http://qiita.com/nyampire/items/a52a4c68b60f6d538c5b).
If any trouble you have, please tell me. I'll delete it or add appropriate attribution.

**Comment by bhousel** [comment]
Thanks @nyampire, this is great!

**Comment by nyampire** [comment]
Thank you so much!
I would like to contribute the other pages as I translated.

On the other hand, I could not find the language switcher on the top of page. 
It seems due to I missed a fix for [translation.yml](https://github.com/mapbox/mapping/blob/mb-pages/_data/translations.yml). I'll send PR later.

If you need more tweak other than that, please inform me.

**Comment by nyampire** [comment]
I've made a PR regarding this issue as #301 .

**Pull request merged**
